apiVersion: v1
kind: Service
metadata:
  name: ka-hs
  labels:
    app: ka
spec:
  ports:
  - port: 9093
    name: server
  clusterIP: None
  selector:
    app: ka
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: ka-pdb
spec:
  selector:
    matchLabels:
      app: ka
  maxUnavailable: 1
---
